#!/bin/ruby

require 'json'
require 'stringio'



#
# Complete the 'fizzBuzz' function below.
#
# The function accepts INTEGER n as parameter.
#

def fizzBuzz(n)
    # Write your code here
    for i in 1..n
        if i%3==0 && i%5==0
            puts "FizzBuzz"
        elsif i%3==0
            puts "Fizz"
        elsif i%5==0
            puts "Buzz"
        else
            puts i
        end
    end
end

n = 15

fizzBuzz n
